name: main_build

on:
  push:
    branches: [ master ]
    
  pull_request:
    types: [opened, synchronize, reopened]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |      
          sudo apt update && sudo apt install -y debootstrap

          sudo bash debootscript.sh -b ${{ github.run_number }}.img -n wibble -t mbr -r stable -u administrator -p password

          sudo xz ${{ github.run_number }}.img

      - uses: actions/upload-artifact@v4
        with:
            name: image-${{ github.run_number }}
            path: ${{ github.run_number }}.img.xz

            

      
